### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by selbyk** [nknapp/swagger-to-html#2]
Just wanted to say nice work and thanks.  =)

It definitely seems like you're the furthest along with translating swagger into bootstrap.  Hopefully I'll throw some contributions your way in the not too distant future.

-Selby
http://selby.io

**Comment by nknapp** [comment]
Hi Selby,

glad you like it. Just in case you missed the deprecation notice in the README.md: `swagger-to-html` moved to `bootprint` (core functionality), `bootprint-base` (base-templates), `bootprint-json-schema` (json-schema-templates) and `bootprint-swagger` (swagger-specific templates). 

So `bootprint` and `bootprint-swagger` are probably what you should be using. I'm currently trying to document those projects properly, to support contributors. It seems to be a long path...
