### ISSUE TITLE
Only works with JSON not YAML

### ISSUE THREAD

**Issue by alexanderhawley** [nknapp/swagger-to-html#4]
What's up with that?

**Comment by nknapp** [comment]
Hi Alexander,

thanks for your post. Please note that this repo is deprecated and will not be maintained anymore.
Please go to [bootprint-swagger](https://github.com/nknapp/bootprint-swagger) which is the replacement for this module and supports a much larger set of the swagger-2.0-spec.

However, YAML-support would have to go into the [bootprint](https://github.com/nknapp/bootprint)-package. There is already [an issue for this](https://github.com/nknapp/bootprint/issues/4) which you can `+1` if you like.

It hasn't been much of a usecase for me yet, I'm fine with JSON. And my primary goal for now was to go for total support for the spec. Some parts are yet missing.
